from pathlib import Path


def test_required_artifacts_exist():
    for path in [
        "paper/main.tex",
        "paper/references.bib",
        "evidence/inventory.md",
        "docs/experiment_protocol.md",
        "docs/claim_boundaries.md",
        "benchmark/cases.jsonl",
    ]:
        assert Path(path).exists(), path


def test_paper_has_no_process_trace_terms():
    text = Path("paper/main.tex").read_text(encoding="utf-8").lower()
    banned = [
        "written by codex",
        "generated by codex",
        "chatgpt wrote",
        "ai-written",
        "during this run",
    ]
    for term in banned:
        assert term not in text
