from pathlib import Path


def test_required_artifacts_exist():
    for path in [
        "paper/main.tex",
        "paper/references.bib",
        "paper/metadata.json",
        "LICENSE",
        "LICENSE-MIT",
        "LICENSE-CC-BY-4.0.md",
        "CITATION.cff",
        ".zenodo.json",
        "artifact_manifest.json",
        "CHANGELOG.md",
        "evidence/inventory.md",
        "evidence/github_evidence.json",
        "evidence/github_snapshots.md",
        "evidence/source_audit.md",
        "experiments/run_manifest.md",
        "results/tables/category_summary.tex",
        "results/tables/failure_taxonomy.tex",
        "results/tables/live_success_uncertainty.tex",
        "results/tables/live_pairwise_delta.tex",
        "docs/experiment_protocol.md",
        "docs/claim_traceability.md",
        "docs/data_dictionary.md",
        "docs/external_decision_register.md",
        "docs/arxiv_endorsement_candidates.md",
        "docs/arxiv_submission.md",
        "docs/arxiv_endorsement_email.md",
        "docs/live_rerun_promotion.md",
        "docs/claim_boundaries.md",
        "docs/artifact_release_index.md",
        "docs/reviewer_guide.md",
        "docs/submission_readiness.md",
        "docs/zenodo_release_plan.md",
        "docs/final_cleanup.md",
        "benchmark/cases.jsonl",
        "scripts/rerun_parse_errors.py",
        "scripts/analyze_uncertainty.py",
        "scripts/check_public_traces.py",
        "scripts/check_artifact_consistency.py",
        "scripts/check_entrypoint_commands.py",
        "scripts/check_release_references.py",
        "scripts/check_validate_workflow_paths.py",
        "scripts/check_status_notes.py",
        "scripts/check_run_manifest_alignment.py",
        "scripts/check_claim_traceability.py",
        "scripts/check_external_decisions.py",
        "scripts/check_archive_manifest_alignment.py",
        "scripts/build_artifact_archive.py",
        "scripts/check_provider_credentials.py",
        "scripts/audit_source_evidence.py",
        "scripts/run_checks.py",
        "scripts/smoke_test.py",
    ]:
        assert Path(path).exists(), path


def test_paper_has_no_process_trace_terms():
    text = Path("paper/main.tex").read_text(encoding="utf-8").lower()
    banned = [
        "written by codex",
        "generated by codex",
        "chatgpt wrote",
        "ai-written",
        "during this run",
    ]
    for term in banned:
        assert term not in text
