from pathlib import Path


def test_required_artifacts_exist():
    for path in [
        "paper/main.tex",
        "paper/references.bib",
        "paper/metadata.json",
        "artifact_manifest.json",
        "CHANGELOG.md",
        "evidence/inventory.md",
        "evidence/github_evidence.json",
        "evidence/github_snapshots.md",
        "evidence/source_audit.md",
        "experiments/run_manifest.md",
        "results/tables/category_summary.tex",
        "results/tables/failure_taxonomy.tex",
        "docs/experiment_protocol.md",
        "docs/claim_boundaries.md",
        "docs/artifact_release_index.md",
        "docs/reviewer_guide.md",
        "docs/submission_readiness.md",
        "docs/final_cleanup.md",
        "benchmark/cases.jsonl",
        "scripts/rerun_parse_errors.py",
        "scripts/check_public_traces.py",
        "scripts/check_artifact_consistency.py",
        "scripts/check_entrypoint_commands.py",
        "scripts/check_release_references.py",
        "scripts/audit_source_evidence.py",
        "scripts/run_checks.py",
    ]:
        assert Path(path).exists(), path


def test_paper_has_no_process_trace_terms():
    text = Path("paper/main.tex").read_text(encoding="utf-8").lower()
    banned = [
        "written by codex",
        "generated by codex",
        "chatgpt wrote",
        "ai-written",
        "during this run",
    ]
    for term in banned:
        assert term not in text
