from __future__ import annotations

from pathlib import Path


PUBLIC_FILES = [
    Path("README.md"),
    Path("CHANGELOG.md"),
    Path("artifact_manifest.json"),
    Path("paper/main.tex"),
    Path("paper/metadata.json"),
    Path("docs/artifact_release_index.md"),
    Path("docs/claim_traceability.md"),
    Path("docs/data_dictionary.md"),
    Path("docs/external_decision_register.md"),
    Path("docs/live_rerun_promotion.md"),
    Path("docs/reproducibility.md"),
    Path("docs/reviewer_guide.md"),
    Path("docs/submission_readiness.md"),
    Path("docs/final_cleanup.md"),
    Path("evidence/inventory.md"),
    Path("evidence/github_evidence.json"),
    Path("evidence/github_snapshots.md"),
    Path("evidence/source_audit.md"),
    Path("evidence/source_audit.json"),
]

BANNED_TERMS = [
    "local codex autoreview",
    "generated by codex",
    "written by codex",
    "created by codex",
    "chatgpt wrote",
    "ai-written",
    "production-ready",
    "metadata proves",
    "script was added after",
    "after the provider wrapper was fixed",
    "c:/users/",
    "project work is on d:",
    ".codex/attachments",
    "codex_reference",
    "run_codex_reference.py",
    "https://github.com/rrrrrredy/ai-radar-web",
    "https://github.com/rrrrrredy/ai-radar-skill",
]


def main() -> None:
    findings: list[str] = []
    for path in PUBLIC_FILES:
        text = path.read_text(encoding="utf-8", errors="ignore").lower()
        for term in BANNED_TERMS:
            if term in text:
                findings.append(f"{path}: {term}")
    if findings:
        raise SystemExit("public trace terms found:\n" + "\n".join(findings))
    print("public trace check passed")


if __name__ == "__main__":
    main()
